// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-SRU0unkd4fvx4KtHyH77Y7oHmMP380I',
    appId: '1:864563231577:android:31cb86e11e3f3630a9ea48',
    messagingSenderId: '864563231577',
    projectId: 'evently-283a2',
    storageBucket: 'evently-283a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8B7ygBYLuFXJr0keR-e4cMCnBN9_Urgg',
    appId: '1:864563231577:ios:23ffcd9100d6197da9ea48',
    messagingSenderId: '864563231577',
    projectId: 'evently-283a2',
    storageBucket: 'evently-283a2.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCc0bKq5SX9GzY3XzHBGDOfDPEeGxCP2-o',
    appId: '1:864563231577:web:d2be9489cf44ca3ca9ea48',
    messagingSenderId: '864563231577',
    projectId: 'evently-283a2',
    authDomain: 'evently-283a2.firebaseapp.com',
    storageBucket: 'evently-283a2.firebasestorage.app',
  );
}
